
version: "3"

services:
  db:
    image: postgres:15.5
    restart: always
    ports:
      - "5432:5432"
    networks:
      - orm_network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

volumes:
  pgdata:

networks:
  orm_network:
    driver: bridge
